name: 'Dispatch notification event'

description: 'Dispatch notification event'

inputs:
  payload:
    description: ''
    required: false
  token:
    description: 'A Github Token'
    required: true

runs:
  using: "composite"
  steps:
      - name: Dispatch notification event
        shell: bash
        run: |
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ inputs.token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/Yakutoc/plasma-dev-stage/dispatches \
              -d "{\"event_type\":\"notification-event\",\"client_payload\":${{ inputs.payload }}}"
