name: 'Draft components'

description: 'Check if change/create draft config components'

runs:
    using: "composite"
    steps:
        -   name: Computed HAS_EXECUTE_STORYBOOK_DRAFT
            shell: bash
            run: |
                if npx lerna diff | grep -E '\.config\.draft\.ts$'; then
                  echo "HAS_EXECUTE_STORYBOOK_DRAFT=true" >> $GITHUB_ENV
                else
                  echo "HAS_EXECUTE_STORYBOOK_DRAFT=false" >> $GITHUB_ENV
                fi

        -   name: ECHO
            shell: bash
            run: echo ${{ env.HAS_EXECUTE_STORYBOOK_DRAFT }}
