name: PR Ready for Review

on:
    pull_request:
        types: [ ready_for_review ]
        branches:
            - dev

jobs:
    review-notification:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Get pull request list (first ~15)
                run: |
                    ## Тут будет action который вернет список первых 15 пр открытых и не черновик
                    echo "Pull request ${{ github.event.pull_request.user.login }}"

            -   name: Get list reviewers
                run: |
                    ## Тут будет action который вернет список reviewers
                    ## фильтр | исключить автора | исключить тех кто имеет больше 4 пр на ревью

            -   name: Set review
                uses: actions/github-script@v7
                with:
                    script: |
                        await github.rest.pulls.requestReviewers({
                          ...context.repo,
                          pull_number: context.payload.pull_request.number,
                          reviewers: ['neretin-trike']
                        });

            -   name: Dispatch event
                uses: ./.github/actions/dispatch-notification-event
                with:
                    message: "Pull request: ${{ github.event.pull_request.title }} готов к осмотру!"
                    token: ${{ secrets.GH_TOKEN }}
