name: PR Ready for Review

on:
    pull_request:
        types: [ ready_for_review ]
        branches:
            - dev

jobs:
    review-notification:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: DUMP
                run: |
                    echo "Pull request #${{ github.event.pull_request.number }} is now ready for review!"
                    echo "Pull request ${{ github.event.pull_request.user.login }}"

            -   name: Set review
                uses: actions/github-script@v7
                with:
                    script: |
                        const teammate = {
                          Yakutoc: "alex_czech",
                          'neretin-trike': "aaneretin",
                          'Yeti-or': "yeti-or",
                          TitanKuzmich: "aakrivonos",
                          shuga2704: "shuga2704",
                          denivladislav: "denivladislav",
                          iljs: "iljaby",
                          'vadim-kudr': "vadimkudryavtsev",
                        };

                        await github.rest.pulls.requestReviewers({
                          ...context.repo,
                          pull_number: context.payload.pull_request.number,
                          reviewers: ['neretin-trike']
                        });

            -   name: Create message
                run: |
                    message='Pull request: ${{ github.event.pull_request.title }} готов к осмотру'

                    echo "NOTIFICATION="$message"" >> $GITHUB_ENV

            -   name: Create the Mattermost Message
                run: |
                    echo "{\"text\":\" ${{ env.NOTIFICATION }}\"}" > mattermost.json

            -   name: Send notification
                uses: mattermost/action-mattermost-notify@2
                with:
                    MATTERMOST_WEBHOOK_URL: ${{ secrets.WEBHOOKS_NOTIFICATIONS_MM }}
