name: Create release LF

on:
    repository_dispatch:
        types: [ release-LF ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # как выбрать в рамках спринта (между 2 мя датами)
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                show-progress: false

            - name: Это данные нужно получить из workflow "Create release PR and generate changelog"
              run: |
                  echo ${{ github.event.client_payload.pull_requests }}

            -   name: Извлечение ID задачи из заголовков PR
                id: extract_ids
                uses: actions/github-script@v7
                with:
                    result-encoding: string
                    script: |
                        const prNumbers = `{{ github.event.client_payload.pull_requests }}`
                            .split(',')
                            .map(num => num.trim());

                        const { title } = await github.rest.pulls.get({
                            owner: 'Yakutoc',
                            repo: 'plasma-dev-stage',
                            pull_number: prNumber
                        });

                        console.log(title);
