# Default based by dev branch
name: Create release pull request

on:
  workflow_dispatch:
    inputs:
      from-tag:
        description: ''
        required: false

jobs:
  release-pr:
    name: Create release PR with changelog
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    outputs:
        pull_requests: ${{ steps.state.outputs.pull_requests }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0

      - name: Computed envs
        run: |
          echo "FROM_TAG=$(git merge-base --fork-point origin/master)" >> $GITHUB_ENV

      - name: Build Changelog
        id: state
        uses: mikepenz/release-changelog-builder-action@v4.1.0
        with:
          fromTag: ${{ env.FROM_TAG }}
          toTag: 'dev'
          configuration: "./.github/changelog-builder-config.json"
