name: Create release LF

on:
    workflow_run:
        workflows:
            - "Create release pull request"
        types:
            - completed
jobs:
    build:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            # как выбрать в рамках спринта (между 2 мя датами)
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                show-progress: false

            - name: Это данные нужно получить из workflow "Create release PR and generate changelog"
              id: tasks
              run: |
                  echo ${{ github.event.workflow_run }}
                  echo ${{ github.event.workflow_run.outputs }}
                  echo ${{ github.event.workflow_run.outputs.pull_requests }}

            -   name: Извлечение ID задачи из заголовков PR
                id: extract_ids
                uses: actions/github-script@v7
                with:
                    result-encoding: string
                    script: |
                        const prNumbers = `{{ github.event.workflow_run.outputs.pull_requests }}`.split(',').map(num => num.trim());

                        const promises = prNumbers.map(async (prNumber) => {
                            const { title } = await github.rest.pulls.get({
                                owner: 'Yakutoc',
                                repo: 'plasma-dev-stage',
                                pull_number: prNumber
                             });

                            console.log(title);

                            const match = title.match(/\[(PLASMA+-\d+)\]/);

                            return match ? match[1] : null;
                        });

                        const results = await Promise.all(promises);

                        const taskIDs = results.filter(Boolean);

                        console.log(taskIDs);
