name: Deploy documentations artefacts [DEMO STAGE]

on:
    workflow_dispatch:

jobs:
    run:
        name: Deploy artifacts [DEMO STAGE]
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ./.github/workflows/documentation-deploy-common.yml
        with:
            path: 'dev'
            ref: 'master'
