# Default based by dev branch
name: DRAFT

on:
    workflow_dispatch:
        inputs:
            sha:
                description: ''
                required: false

jobs:
    geeet:
        name: 'DRAFT'
        runs-on: ubuntu-22.04
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        steps:
            - name: Get pull requests id's
              id: ids
              uses: actions/github-script@v7
              with:
                  script: |
                      const res = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                          commit_sha: `${{ inputs.sha }}`,
                          owner: 'salute-developers',
                          repo: 'plasma',
                      });

                      const data = res?.data[0].body || '';

                      const prRegex = /\[PR\]\(https:\/\/github\.com\/[^\/]+\/[^\/]+\/pull\/(\d+)\)/g;

                      const matches = Array.from(data.matchAll(prRegex));

                      const ids = matches.map(match => parseInt(match[1], 10));

                      return ids[0];

            - name: ECHO
              run: |
                  echo ${{ steps.ids.outputs.result }}

            - name: add comments
              uses: actions/github-script@v7
              with:
                  github-token: ${{ secrets.GH_TOKEN }}
                  script: |
                      const prNumber = parseInt(${{ steps.ids.outputs.result }}, 10);

                      const commentBody = `
                      This PR is included in version:
                            - @salutejs/plasma-giga@0.306.0
                            - @salutejs/plasma-new-hope@0.323.0
                      `;

                      await github.rest.issues.createComment({
                            owner: 'salute-developers',
                            repo: 'plasma',
                            issue_number: prNumber,
                            body: commentBody
                      });
