name: DRAFT

on:
    workflow_dispatch:
        inputs:
            sha:
                description: ''
                required: false

jobs:
    geeet:
        name: 'DRAFT'
        runs-on: ubuntu-22.04
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  repository: salute-developers/plasma
                  ref: master
                  show-progress: false
                  fetch-depth: 10

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: npm

            - name: Get commit message
              run: |
                  COMMIT_SHA=$(git log --all --format="%H %P %s" | grep "${{ inputs.sha }}" | grep "Bump independent versions \[skip ci\]" | awk '{print $1}')
                  COMMIT_MESSAGE=$(git show -s --format=%B "$COMMIT_SHA")
                  echo "COMMIT_MESSAGE<<EOF" >> $GITHUB_ENV
                  echo "$COMMIT_MESSAGE" >> $GITHUB_ENV
                  echo "EOF" >> $GITHUB_ENV

            - name: ECHO
              run: |
                  echo "${{ env.COMMIT_MESSAGE }}"

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                cd .github/actions/add-comment
                npm ci

            - name: Add comment with list version
              uses: ./.github/actions/add-comment
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  message: ${{ env.COMMIT_MESSAGE }}
                  sha: ${{ inputs.sha }}
