name: POC Trigger Target Workflow

on:
    workflow_dispatch:

jobs:
    trigger:
        runs-on: ubuntu-latest
    steps:
        - name: Trigger Workflow in Another Repository
          run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/PoligonSa/plasma-sandbox/dispatches \
            -d '{"event_type":"plasma-trigger","client_payload":{"released":"true"}}'
