name: TEST

on:
    workflow_dispatch:
    pull_request_review:
        types: [ submitted ]

jobs:
    check-approvals:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Count Approvals Using GitHub Script
                id: count_approvals
                uses: actions/github-script@v7
                with:
                    script: |
                        const fs = require('fs');
                        const path = '.github/teammates.json';
                        const teammates = JSON.parse(fs.readFileSync(path, 'utf8'));

                        console.log(teammates);

                        const { data: reviews } = await github.rest.pulls.listReviews({
                          owner: 'salute-developers',
                          repo: 'plasma',
                          pull_number: 1364,
                        });

                        const approvals = reviews.filter(({ state }) => state === 'APPROVED').length;

                        return { approved: approvals >= 2, author: teammates["vadim-kudr"] };

            -   name: Send notification
                if: false
                uses: mattermost/action-mattermost-notify@master
                with:
                    MATTERMOST_WEBHOOK_URL: ${{ secrets.WEBHOOKS_NOTIFICATIONS_MM }}
                    TEXT: |
                        Code review пройдено ✅

                        **PR**: [github.event.pull_request.title](github.event.pull_request.html_url)
                        **Автор**: ${{ github.event.pull_request.user.login }}
