name: TEST

on:
    workflow_dispatch:
    pull_request_review:
        types: [ submitted ]

jobs:
    check-approvals:
        runs-on: ubuntu-latest
        env:
            TITLE: ${{ github.event.pull_request.title || 'Title pr' }}
            URL: ${{ github.event.pull_request.html_url || 'https://github.com/salute-developers/plasma/pulls' }}
            AUTHOR: ${{ github.event.pull_request.user.login || 'Yakutoc' }}
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Count Approvals Using GitHub Script
                id: state
                uses: actions/github-script@v7
                with:
                    script: |
                        const fs = require('fs');
                        const path = '.github/teammates.json';
                        const teammates = JSON.parse(fs.readFileSync(path, 'utf8'));

                        const { data: reviews } = await github.rest.pulls.listReviews({
                          owner: 'salute-developers',
                          repo: 'plasma',
                          pull_number: 1364,
                        });

                        const approvals = reviews.filter(({ state }) => state === 'APPROVED').length;

                        return { approved: approvals >= 2, author: teammates["${{ env.AUTHOR }}"] };

            -   name: ECHO
                run: |
                    echo ${{ fromJSON(steps.state.outputs.result).approved }}
                    echo ${{ fromJSON(steps.state.outputs.result).author }}

            -   name: Send notification
                if: ${{ steps.state.outputs.result.approved == true }}
                uses: mattermost/action-mattermost-notify@master
                with:
                    MATTERMOST_WEBHOOK_URL: ${{ secrets.WEBHOOKS_NOTIFICATIONS_MM }}
                    TEXT: |
                        Code review пройдено ✅

                        **PR**: [${{ env.TITLE }}](${{ env.URL }})
                        **Автор**: @${{ steps.state.outputs.result.author }}
