name: TEST

on:
    workflow_dispatch:
    pull_request_review:
        types: [ submitted ]

jobs:
    check-approvals:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Count Approvals Using GitHub Script
                id: count_approvals
                uses: actions/github-script@v7
                with:
                    script: |
                        const { data: reviews } = await github.rest.pulls.listReviews({
                          owner: 'salute-developers',
                          repo: 'plasma',
                          pull_number: 1364,
                        });

                        const approvals = reviews.filter(({ state }) => state === 'APPROVED').length;

                        return approvals;

            -   name: Dispatch event
                if: ${{ steps.get_approvals.outputs.APPROVALS >= 2 }}
                uses: ./.github/actions/dispatch-notification-event
                with:
                    #message: "**Название**: ${{ github.event.pull_request.title }}\n **PR**: ${{ github.event.pull_request.html_url }}\n **Автор**: ${{ github.event.pull_request.user.login }}"
                    message: "**Название**: Прка \n **PR**: link \n **Автор**: @alex_czech "
                    token: ${{ secrets.GH_TOKEN }}
